language: php
php:
  - 7.1

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit --filter="SetClient"

env:
  - secure: "FDRjP/9HDULpx8ps01Tz81aNUOi8v7b0UOzTAEfhNVbCVUTCJC88MmAXduyGmxFi4n1qzbJ9RxSITNCe9FhxEqY2PCyu8b4GXBF9qutdP8c9XqlD/2DLGcP0KVmJ9YsYuRG+dMeKWV3ZIOM2dSmln6yuI0e0s/+gN/1s45k5LWABgjGRCadk1XRkqmtLeJ999bO6sayBw60jN/btbfiMXSAiBe1UsYYX2EQHboA33L6c/kABLl5wrgcTyvRFNufErjZ00y7vitwdG3Q7ATJL0OcnCM36wc920+pFvfMjGZadjR89s0rjh91tgHGhMob3K5srtTsSGy2/ZjSrr2SlA5YjoC0K55Qed1QCHdPABlBld6WQf8uosqCPNE/Sf+YsTTh/IRzMMuhfjmsakA72gOBY2N/40X4eD8ccpgm5XxvXQiTPDmXkQyivuT8EpG8EMx3USh4mT7e9ui8TNSWthDWiv7P58AIVqaoByE9X8iQwp1QvQqcQU7M6cR0+l0mPptly6mmL6dXlFd4UO3IdiqOlSUy+q63CwMlfSt2IV72zRxYbiRUYml177Ibg3wrYMeNjr7aL/oGkMheXz24KUvwcuGbiFojm8YoT91PdMGymklzr9o+ITYddFX6PdRxn67F6FRH05UYQrGWKXROnd8lE59qhyS2scublGM6kheY="

branches:
  only:
  - master
  - "/^v?[0-9\\.]+/"
